# Generated by Django 2.1.2 on 2018-10-11 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 12, 3, 8, 28, 764912)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 12, 3, 8, 28, 764912)),
        ),
    ]
