# Generated by Django 2.1.2 on 2018-10-11 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181012_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 12, 3, 8, 48, 5208)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 12, 3, 8, 48, 5208)),
        ),
    ]
