# Generated by Django 2.1.2 on 2018-10-12 04:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181012_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 12, 10, 2, 40, 188039)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.Posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 12, 10, 2, 40, 188039)),
        ),
    ]
