# Generated by Django 2.1.1 on 2018-09-30 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('finished_date', models.DateTimeField()),
                ('owner', models.CharField(choices=[('AD', 'Admin'), ('US', 'User'), ('GU', 'Guest')], default='AD', max_length=2)),
                ('mark', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Task_list'),
        ),
    ]
