# Generated by Django 2.1.1 on 2018-10-08 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(verbose_name='Created date')),
                ('finished_date', models.DateTimeField(verbose_name='Finished date')),
                ('owner', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('GUEST', 'Guest')], default='ADMIN', max_length=250)),
                ('mark', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.DateTimeField(verbose_name='Created time of list is')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Task_list'),
        ),
    ]
